############# IMPORTANT ##############
# When upgrading the RuboCop gem,
# ensure that new cops do not heavily
# modify the existing style.
# Disable any of these new cops.
######################################
AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false
 
Security/Eval:
  Exclude:
    - "modules/owner/eval.rb"

Lint/Debugger:
  Exclude:
    - "main.rb"

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Exclude:
    - "config/custom/custom.sample.rb"
  Max: 100

Security/Open:
  Exclude:
    - "modules/helper/download.rb"

# Keep to syntactic linting, instead of complexity.
Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
