source 'http://rubygems.org'
gem 'discordrb', git: 'https://github.com/meew0/discordrb.git'
gem 'rumoji'
gem 'rainbow'
gem 'rake'
gem 'rqrcode'
gem 'commandrb', git: 'https://github.com/Seriell/commandrb.git'
gem 'haste'
gem 'easy_translate', git: 'https://github.com/seejohnrun/easy_translate.git'
gem 'pomf.rb'
gem 'sqlite3'