source 'http://rubygems.org'
gem 'discordrb', git: 'https://github.com/meew0/discordrb.git'
gem 'rumoji'
gem 'rainbow'
gem 'rake'
gem 'rqrcode'
gem 'commandrb', git: 'https://github.com/SuperFrosty/commandrb.git'
