source 'http://rubygems.org'
gem 'commandrb', git: 'https://owo.codes/Seriel/commandrb.git', branch: 'seriel-ownerfix1'
gem 'discordrb'
gem 'easy_translate', git: 'https://github.com/seejohnrun/easy_translate.git'
gem 'haste'
gem 'pomf.rb'
gem 'pry'
gem 'rainbow'
gem 'rake'
gem 'redis'
gem 'redis-namespace'
gem 'rqrcode'
gem 'rumoji'

