name: Build and deploy Docker image(s)

on:
  push:
    branches: 
      - main

jobs:
  docker-deploy:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
          persist-credentials: false
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: yuuki-discord
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push the application
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          builder: builder
          tags: |
            yuukibot/yuukichan:latest
            ghcr.io/yuuki-discord/yuuki-bot:latest
